### ISSUE TITLE
Option to keep vertical spacing

### ISSUE THREAD

**Issue by pbsladek** [adamvoss/vscode-yaml-languageservice#4]
```yaml
database:

  mysql:
    core: null
```

Often I use vertical space to make it a little easier on the eyes. Possible to add an option to support this?
